/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 1.7.0
 *
 * Project: 'Release+Device' 
 * Target:  'Release+Device' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ARMCM0plus.h"

/* GorgonMeducer::Utilities:perf_counter:Core:Library:2.1.0 */
#define __PERF_COUNTER__ 1
/* LVGL.LVGL::LVGL:lvgl:Demo:Widgets:8.3.7 */
/*! \brief enable demo:widgets support */
#define LV_USE_DEMO_WIDGETS         1
/* LVGL.LVGL::LVGL:lvgl:Essential:8.3.7 */
/*! \brief Enable LVGL */
#define RTE_GRAPHICS_LVGL
/* LVGL.LVGL::LVGL:lvgl:Extra Themes:8.3.7 */
/*! \brief use extra themes, widgets and layouts */
#define RTE_GRAPHICS_LVGL_USE_EXTRA_THEMES
/* LVGL.LVGL::LVGL:lvgl:Libs GIF:8.3.7 */
/*! \brief enable gif support */
#define LV_USE_GIF         1


#endif /* RTE_COMPONENTS_H */
