/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 1.7.0
 *
 * Project: 'Debug+Device' 
 * Target:  'Debug+Device' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* GorgonMeducer::Utilities:perf_counter:Core:Library:2.1.0 */
#define __PERF_COUNTER_CFG_USE_SYSTICK_WRAPPER__ 1
/* LVGL.LVGL::LVGL:lvgl:Essential:8.3.7 */
/*! \brief use lv_config_cmsis.h which will be pre-included */
#define LV_CONF_SKIP
#define LV_LVGL_H_INCLUDE_SIMPLE    1


#endif /* PRE_INCLUDE_GLOBAL_H */
